# Generated by Django 2.2 on 2022-08-24 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package_name", models.CharField(max_length=255, null=True)),
                (
                    "package_image",
                    models.ImageField(
                        default="default_product_image.jpg", null=True, upload_to=""
                    ),
                ),
            ],
            options={
                "verbose_name": "Package",
                "verbose_name_plural": "Packages",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255, null=True)),
                (
                    "product_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "product_price",
                    models.DecimalField(decimal_places=0, max_digits=4, null=True),
                ),
                (
                    "product_commission",
                    models.DecimalField(decimal_places=0, max_digits=4, null=True),
                ),
                (
                    "product_color",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "product_image",
                    models.ImageField(
                        default="default_product_image.jpg", null=True, upload_to=""
                    ),
                ),
                ("product_description", models.TextField(null=True)),
                ("product_session_url", models.URLField(max_length=250, null=True)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="SizeAmount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=6, null=True)),
                ("amount", models.PositiveIntegerField(null=True)),
                ("amount_is_empty", models.BooleanField(default=False)),
                ("amount_renewable", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="size_amount",
                        to="product.Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Size and Amount",
                "verbose_name_plural": "Sizes and Amounts",
            },
        ),
    ]
