# Generated by Django 2.2 on 2022-08-24 14:58

import django.db.models.deletion
from django.db import migrations, models

import custome_utils.my_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wallet_potential_commission",
                    models.DecimalField(
                        blank=True, decimal_places=0, default=0, max_digits=4, null=True
                    ),
                ),
                (
                    "wallet_total_commission",
                    models.DecimalField(
                        blank=True, decimal_places=0, default=0, max_digits=4, null=True
                    ),
                ),
                (
                    "marketer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="users.Marketer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MoneyRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "money_request_status",
                    models.CharField(
                        choices=[
                            ("under review", "under review"),
                            ("money sent", "money sent"),
                        ],
                        default="under review",
                        max_length=100,
                    ),
                ),
                (
                    "money_receive_number",
                    models.CharField(
                        max_length=11,
                        null=True,
                        validators=[custome_utils.my_validators.validate_mobile_number],
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        max_length=14,
                        null=True,
                        validators=[custome_utils.my_validators.validate_id_number],
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "marketer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="money_requests",
                        to="users.Marketer",
                    ),
                ),
            ],
        ),
    ]
