# Generated by Django 2.2 on 2022-08-24 14:58

import django.db.models.deletion
from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CitiesDeliver",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_name", models.CharField(max_length=255, null=True)),
                (
                    "city_delivery_price",
                    models.DecimalField(decimal_places=0, max_digits=4, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("under review", "under review"),
                            ("refused", "refused"),
                            ("confirmed", "confirmed"),
                            ("in his way", "on the way"),
                            ("returned", "returned"),
                            ("paid", "paid"),
                        ],
                        default="under review",
                        max_length=20,
                    ),
                ),
                ("order_code", models.CharField(blank=True, max_length=100, null=True)),
                ("order_client_name", models.CharField(max_length=100, null=True)),
                (
                    "order_client_number",
                    models.CharField(
                        max_length=11,
                        null=True,
                        validators=[users.validators.validate_mobile_number],
                    ),
                ),
                (
                    "order_client_number2",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        validators=[users.validators.validate_mobile_number],
                    ),
                ),
                ("order_client_city", models.CharField(max_length=100, null=True)),
                ("order_client_area", models.CharField(max_length=255, null=True)),
                ("order_client_address", models.CharField(max_length=255, null=True)),
                (
                    "order_delivering_price",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("order_notes", models.TextField(blank=True, null=True)),
                (
                    "order_total_price",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=4, null=True
                    ),
                ),
                (
                    "order_total_commission",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=4, null=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("order_confirmed", models.BooleanField(default=False)),
                ("calculated", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.CreateModel(
            name="OrderProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "product_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "product_price",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=4, null=True
                    ),
                ),
                (
                    "product_commission",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=4, null=True
                    ),
                ),
                (
                    "product_image",
                    models.ImageField(
                        blank=True,
                        default="default_product_image.jpg",
                        null=True,
                        upload_to="",
                    ),
                ),
                ("product_size", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "product_quantity",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "product_total_price",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=4, null=True
                    ),
                ),
                (
                    "product_total_commission",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=4, null=True
                    ),
                ),
                (
                    "product_order",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="order_app.Order",
                    ),
                ),
            ],
        ),
    ]
